### ISSUE TITLE
It stopped working today

### ISSUE THREAD

**Issue by Sneffel** [ericchase/addon--maximize-all-windows#9]
Why?

**Comment by ericchase** [comment]
Idk, why did you stop working?

**Comment by Sneffel** [comment]
It doesn't maximize them tabs any more.

**Comment by ericchase** [comment]
Still works

Uploading 2022-10-23_09.08.11.mp4…

**Comment by Sneffel** [comment]
So why doesn't it work on my machine any more? It only works in private browsing

**Comment by ericchase** [comment]
Well, I couldn't possibly know. But the most likely reason is that you changed something. Maybe you added a conflicting extension? Maybe changed a setting that doesn't allow this one to work anymore. It's very hard to know exactly why unless you compare your browser installation with a fresh one.

**Comment by ericchase** [comment]
I've had issues before myself when extensions suddenly stop working. If you can't figure out why, then you might just need to do a fresh install of the browser. It's a pain, and you need to backup your bookmarks, settings, and the settings of your other extensions.

Also keep in mind that some browsers may perform random A/B testing. It's unlikely, but possible.

My first guess would be that you installed another extension that is conflicting with mine. This one is pretty easy to find out. Just disable all your other extensions and see if mine works again.

My second would be that you somehow turned on some security settings that don't allow windows to be resized automatically. This one would be very hard to figure out, because there are tons of settings in browsers.

There's not much else I can do, except *maybe* look at your installation if you feel comfortable sharing your browsers profile folder. Doing so would be a huge privacy/security risk, but if you're desperate, you know...

**Comment by ericchase** [comment]
Oh, also make sure the options in my extension are turned on.

**Comment by Sneffel** [comment]
I "refreshed" FF and now everything works again.
I tried removing every add-on and deleting everything from about:config but that didn't help. 
I hope this problem won't come up again.
And I've just realized the title. I'm still working. Thanks.

**Comment by Sneffel** [comment]
No, it still doesn't work every time. It works once and doesn't work three times. It's a lottery.

**Comment by ericchase** [comment]
That is very strange

**Comment by Sneffel** [comment]
I installed nightly and as expected there's no problem.
Maybe sync synchronizes something else other than about:config
What could it be?

**Comment by ericchase** [comment]
I really don't know. The only setting I messed with that I know could cause problems are the fingerprinting settings in about:config.

**Comment by Sneffel** [comment]
![ssss](https://user-images.githubusercontent.com/9219144/197965665-8a3d9025-db02-4994-a3db-c0b1998b4ecf.png)
I reverted everything
What's bugging me is that it's a new machine I've just set up with minimal settings tweaking.
But Nightly is fine

**Comment by ericchase** [comment]
Right, my copies of stable and dev seem to be working as expected still. I can't think of any particular reasons why it randomly doesn't work for some installations. If I see any problems later on, I'll try to figure out why

**Comment by Sneffel** [comment]
It doesn't work on Nightly too now.
I think it slowly synchronizes an about:config setting. I set every _services.sync.prefs.sync_.X to false, but it still doesn't work now 100% of the time.
Are there any further tests I can perform to isolate the issue?

**Comment by ericchase** [comment]
One of the fingerprinting settings doesn't allow windows to open maxized. No settings are checked in the code. There might be some timing issues, but I don't know. In the future, extension code will probably restricted more, just like in Google, then I'll have to rewrite the extension anyways with less features

**Comment by ericchase** [comment]
You can always download the project and fiddle with the code yourself if you want. You can test by opening the main folder with the manifest file as an unpacked extension in Firefox

**Comment by Sneffel** [comment]
I don't know anything about browser extensions so I wouldn't be very helpful. Thanks for the help and for the patience.
